// Build the embeddable bundle: client/dist/vgo-bot.js
//
//     npm --prefix client run build
//
// One file, no dependencies, no bundler. The engine's WebAssembly is inlined as
// base64 so a host has a single artefact to serve, which matters more than the
// ~33% base64 overhead: the failure this prevents is a page that loads the
// module and then 404s on a .wasm nobody remembered to copy.
//
// What is *not* inlined, and will not be: onnxruntime-web and the model.
// onnxruntime-web ships its own multi-megabyte WASM binaries per backend, and
// the model is tens of megabytes; both want to be cached by the host on its own
// terms, and both are already artefacts a host serves deliberately. Inlining
// them would turn a 365 KB module into a 60 MB one that cannot be cached
// separately from the code.
//
// The bundling is textual, on three known lines of wasm-bindgen's output and one
// of ours. That is fragile in exactly one way -- a wasm-bindgen upgrade could
// change the shape -- so every substitution is asserted. A failed assertion here
// is the intended behaviour: it stops a silently broken bundle from shipping.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const vendor = join(here, 'vendor');
const out = join(here, 'dist', 'vgo-bot.js');

/// Replace exactly once, or explain what changed underneath us.
function replaceOnce(text, find, replacement, what) {
  const parts = text.split(find);
  if (parts.length !== 2) {
    throw new Error(
      `expected exactly one ${what} in the generated glue, found ${parts.length - 1}.\n` +
      `Looked for: ${JSON.stringify(find)}\n` +
      'wasm-bindgen probably changed its output shape; check client/build.js.',
    );
  }
  return parts.join(replacement);
}

const [glueSource, wasmBytes, apiSource] = await Promise.all([
  readFile(join(vendor, 'vgo_wasm.js'), 'utf8'),
  readFile(join(vendor, 'vgo_wasm_bg.wasm')),
  readFile(join(here, 'src', 'index.js'), 'utf8'),
]);

// The glue is a module with three exports and no imports, which is what makes
// concatenation safe: turn the exports into plain declarations and it becomes an
// ordinary block of code.
let glue = glueSource;
glue = replaceOnce(glue, 'export class Game {', 'class Game {', 'Game export');
glue = replaceOnce(glue, 'export class Search {', 'class Search {', 'Search export');
glue = replaceOnce(
  glue,
  'export { initSync, __wbg_init as default };',
  '// exports folded into the bundle below',
  'export list',
);
if (/^\s*import\s/m.test(glue)) {
  throw new Error('the generated glue now has imports; concatenating it is no longer safe');
}

// Our module imports exactly one thing, from the glue we just inlined.
let api = replaceOnce(
  apiSource,
  "import initWasm, { Game } from '../vendor/vgo_wasm.js';",
  'const initWasm = __wbg_init;',
  'engine import',
);
api = replaceOnce(
  api,
  'const INLINE_WASM_BASE64 = null;',
  `const INLINE_WASM_BASE64 = ${JSON.stringify(wasmBytes.toString('base64'))};`,
  'inline-wasm placeholder',
);

const banner = `// Voronoi Go bot -- generated by client/build.js, do not edit.
//
// Contains crates/vgo-wasm compiled to WebAssembly and inlined, plus the API in
// client/src/index.js. Rules and search are the same code self-play runs.
//
// Needs onnxruntime-web and an exported model, neither of which is bundled:
//
//     import { createBot } from './vgo-bot.js';
//     import * as ort from './ort.all.min.mjs';
//     const bot = await createBot({ ort, modelUrl: '/vgo/model.onnx' });
//     const move = await bot.chooseMove(position, { thinkMillis: 5000 });
`;

await mkdir(dirname(out), { recursive: true });
await writeFile(out, `${banner}\n${glue}\n${api}`);

const bytes = (await readFile(out)).length;
console.log(`${out}  ${(bytes / 1024).toFixed(0)} KB  (wasm ${(wasmBytes.length / 1024).toFixed(0)} KB inlined)`);
