#!/usr/bin/env bash
# ddrnet-attn-komi.sh continued from update 140, with search doubled:
# 3200 simulations for generation and 1200 for soft-resigned play.
#
#   ./runs/ddrnet-deep.sh                         # -> artifacts/ddrnet-deep
#   VGO_UPDATES=60 ./runs/ddrnet-deep.sh          # longer
#   ./runs/ddrnet-deep.sh artifacts/my-run        # somewhere else
#
# Run it from the project root. A relative output directory is pinned to the
# invoking shell below, and --initial-replay paths are derived from it; those
# paths are part of run identity, so invoking from a different directory with a
# different relative path would make the run unresumable.
#
# WHY THIS RUN EXISTS
#
# ddrnet-attn-komi stopped improving. Measured by play on 2026-08-15
# (artifacts/run-finals/RESULT.md): its final model, update 140, is +18 +/- 51
# Elo against update 61, its state 79 updates and ~15 hours earlier, and it lost
# that head-to-head 9-11. The same tournament separates seven run-finals across
# 799 Elo at p = 0.000, so that is a null result and not a blind instrument.
# The run's own promotion arena agrees: acceptance fell from 27/62 (44%) over
# updates 0-61 to 23/83 (28%) over 62-144.
#
# Both of those are strength measured by play, which is the only evidence this
# recipe rests on. An earlier draft of this header also cited the training
# telemetry -- "49 of 83 updates had best_epoch 0, so their epoch was
# discarded". That was wrong twice over and is recorded here so it is not
# repeated: the loop publishes the final epoch unconditionally
# (learner.py:1650, "Publish the last epoch, not the best-scoring one"), so
# nothing is ever discarded; and best_epoch is explicitly documented there as
# noise-dominated, because the validation split hashes ~38 *games* and every
# ply of a game shares one terminal value, putting the standard error of the
# selection metric at roughly four times the difference being measured. Nor are
# validation *levels* comparable across updates: the split is redrawn from the
# current window each time, so those are different datasets.
#
# The hypothesis is unchanged. At 1600 simulations the search targets were no
# longer ahead of the network producing them, so each new shard carried nothing
# to learn. Doubling the search moves the target back in front of the model.
#
# WHY GENERATION SIMULATIONS ARE AN IDENTITY FIELD, AND THIS IS A NEW RUN
#
# `generation_simulations` and `resign_soft_simulations` are not in
# OPERATIONAL_CONFIG_FIELDS (pipeline.py:34), so changing either makes the
# coordinator refuse to resume ddrnet-attn-komi -- deliberately, since a run
# whose search budget changed midway is two experiments sharing a directory.
# Seeding from its last accepted checkpoint keeps the 21 hours already spent.
#
# WHY UPDATE 140 AND NOT 144
#
# 144 is the highest-numbered directory but it is a *rejected* candidate: it
# lost its promotion arena 6-10 and was discarded. `models` in
# pipeline-state.json is the lineage; its last entry is 140. Note that this is
# also why ratings.json cannot be used to pick a seed -- build-dense-curve rates
# every exported candidate.onnx, so its "best checkpoint" for this run (update
# 58, 1314 Elo) is a rejected candidate too.
#
# WHY SHARDS 139-144 SEED THE REPLAY WINDOW
#
# They are the live window at the parent's end: uncompressed (135-138 have been
# retired to .zst and cannot be copied), all generated after the game.rs
# even-trade fix landed at shard 83, and 142-144 were generated by update 140
# itself -- the exact checkpoint this run starts from. Without them the first
# updates would train a model accustomed to a 32k-sample window on a single
# 5.2k shard.
#
# They were generated at 1600/800, so the first six updates train on a mix of
# old-depth and new-depth targets before ageing out. That is the intended cost:
# a cold window is worse than a slightly stale one.
#
# Copied rather than referenced, for the reason the parent recipe gives:
# retirement deletes the uncompressed original once a shard leaves the window
# (pipeline.py:119), so pointing at the parent's replay directory would rewrite
# ddrnet-attn-komi's last six shards as a side effect of this run's own
# housekeeping.
#
# WHY THE SOFT COUNT IS 1200 AND NOT 1600
#
# Soft resign is doing more work than its name suggests. Over shards 120-144 it
# fired in 88% of games, and because the losing streak accumulates before
# --resign-minimum-ply the concession lands at ply 20-21 in most of them. The
# result is that **40% of all plies are already played at the soft count**, not
# a thin endgame tail.
#
# That is not waste, though it looks like it. Those games really are decided:
# the komi draw settles most of them before play, with Black winning 96% of
# games drawn below komi 0.00 and 5% of those above 0.22. Cheap search on a
# decided game is the resign mechanism working.
#
# But it does mean the soft count governs a large minority of positions rather
# than a tail, so it belongs in the budget arithmetic rather than being ignored.
# Mean simulations per ply go from 0.6*1600 + 0.4*800 = 1280 to
# 0.6*3200 + 0.4*1200 = 2400 -- 1.875x, not the 2x the generation number alone
# suggests. 1200 puts the soft ratio at 0.375 against the parent's 0.5, which
# buys back some of the cost of the deeper main search.
#
# WHAT IS DELIBERATELY UNCHANGED, AND THE OPEN QUESTIONS THAT GO WITH IT
#
# Everything from --resolution down is byte-identical to ddrnet-attn-komi.sh
# apart from the two simulation counts and the seeds. Three things measured
# during this investigation argue for changing more, and are left alone here so
# that this run isolates the search-depth change. They are written down so the
# next run does not have to rediscover them:
#
#   Komi width. --komi-low/--komi-high span 0.4, and across that span the Black
#   win rate runs from 96% to 5%. Only the middle is competitive, and even there
#   it is 74% and 18% in the two central quarters. Roughly 29% of games are
#   foregone from the draw. Narrowing the width would raise the share of games
#   that are actually contested -- probably a bigger lever on target quality
#   than depth -- at the cost of the komi channel seeing a narrower range.
#
#   Promotion arena size. --arena-pairs 8 is 16 games against a 0.55 threshold,
#   at which a candidate *identical* to its parent is rejected 60-77% of the
#   time. It rejected 60 of 83 overnight candidates. The gate is close to a coin
#   flip; either raise it to ~32 pairs or drop it entirely.
#   RESOLVED 2026-08-16: the promotion gate was removed from the pipeline, so
#   the flags this run was launched with no longer exist. This run's own
#   acceptance record stands as written; runs after that date publish every
#   candidate and rate them afterwards with --telemetry-every.
#
#   Ply cap. 13% of games over shards 120-144 reach --maximum-plies 70 and are
#   adjudicated by area rather than played out, at a median length of 57. Deeper
#   search may lengthen games further and push that higher.
#
# Resignation stays at 0.02/1200/0.0 and the window at 5. All are identity
# fields: editing them after launch does not reconfigure the run, it makes the
# coordinator refuse to resume it. See the incident recorded in
# ddrnet-attn-komi.sh -- a recipe for a live run is a record of that run, not a
# place to stage the next experiment.
#
# SIZING
#
# The parent generated a shard in 610s at 1600/800. Search work scales with
# mean simulations per ply, 1280 -> 2400 = 1.875x, so expect roughly 1150s a
# shard and about 20 minutes an update against the parent's 11. A 15-hour
# window is therefore closer to 45 updates than 83, which is the trade this run
# is making: fewer updates against targets that are actually ahead of the model.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${1:-$root/artifacts/$(basename "${BASH_SOURCE[0]}" .sh)}"
case "$out" in /*) ;; *) out="$PWD/$out" ;; esac

# Refuse to write into a run this recipe did not create.
#
# A recipe derives its output directory from its own filename, so naming a new
# recipe after an existing run points it straight at that run's directory. The
# coordinator does catch the collision -- it compares config digests and refuses
# to resume -- but only after this script has already copied 150 MB of seed
# replay in, appended to the run's log, and overwritten its launch.sh, which for
# a run predating tracked recipes is the only description of it that exists.
# That happened to artifacts/ddrnet-deep on 2026-08-15; the launch.sh was not
# recoverable, since artifacts/ is gitignored.
#
# So the check has to come before any of those writes, not after. A directory
# holding pipeline-config.json but no seed-replay is a run some other recipe
# created: this one always makes seed-replay before the coordinator writes any
# config, so that combination cannot be its own.
if [ -f "$out/pipeline-config.json" ] && [ ! -d "$out/seed-replay" ]; then
  echo "refusing to write into $out: it holds another run's pipeline-config.json" >&2
  echo "pick a different output directory, or rename this recipe" >&2
  exit 1
fi

mkdir -p "$out/logs"

parent="$root/artifacts/ddrnet-attn-komi"
parent_update="$parent/updates/update-000140"
# --initial-checkpoint below spells this path out as "$root/..." rather than
# reusing $parent_update. scripts/rate-checkpoints.py recovers the parent run by
# regex over this file (rate-checkpoints.py:98) and that pattern only
# understands a literal `root`; through a different variable the lineage
# silently reads as "no parent" and this run gets rated as if it started cold.

seed="$out/seed-replay"
if [ ! -d "$seed" ]; then
  echo "=== seeding replay from $parent (147 MB)"
  mkdir -p "$seed"
  for shard in 000139 000140 000141 000142 000143 000144; do
    cp -r "$parent/replay/shard-$shard" "$seed/shard-$shard"
  done
fi

install -m 755 "${BASH_SOURCE[0]}" "$out/launch.sh"

exec > >(tee -a "$out/logs/run.log") 2>&1
echo "=== $(date -Is) starting, output $out"
echo "=== seeded from $parent_update, generation 3200 / soft 1200"

cd "$root/training"
exec .venv/bin/python3 -m vgo_training.rl_loop \
  --output "$out" \
  --updates "${VGO_UPDATES:-45}" \
  --initial-checkpoint "$root/artifacts/ddrnet-attn-komi/updates/update-000140/candidate.pt" \
  --initial-onnx "$root/artifacts/ddrnet-attn-komi/updates/update-000140/candidate.onnx" \
  --initial-replay \
    "$seed/shard-000139" "$seed/shard-000140" "$seed/shard-000141" \
    "$seed/shard-000142" "$seed/shard-000143" "$seed/shard-000144" \
  --samples-per-shard 1600 --shards-per-update 1 --replay-window 6 \
  --resolution 128 --policy-resolution 128 --radius 0.055714285714285716 \
  --raster-kind compact --komi-low=-0.166 --komi-high=0.234 \
  --dynamic-komi --komi-target-black-win-rate 0.5 \
  --komi-recenter-minimum-games 256 --komi-recenter-maximum-step 0.025 \
  --coarse-pool 16 --generation-simulations 3200 \
  --temperature 1.0 --temperature-plies 30 --maximum-plies 70 \
  --resign-target-false-positive 0.02 --resign-soft-simulations 1200 \
  --resign-window 5 --resign-minimum-ply 20 --resign-disable-fraction 0.0 \
  --training-epochs 1 --training-batch 256 \
  --learning-rate 0.001 --warm-learning-rate 0.001 --value-weight 2.0 \
  --ownership-weight 0.0 --recency-decay 1.0 --drain-tail \
  --concurrent-generators 1 \
  --schedule cosine --warmup-epochs 0 --compile --restore-optimizer \
  --architecture ddrnet --norm-groups 8 --model-width 64 --blocks 16 \
  --context-attention-blocks 1 --attention-heads 8 \
  --full-adam \
  --training-device cuda --training-threads "${VGO_TRAINING_THREADS:-4}" \
  --report-every 1 --validation-fraction 0.1 \
  --actors "${VGO_ACTORS:-64}" --arena-actors "${VGO_ARENA_ACTORS:-${VGO_ACTORS:-64}}" \
  --leaf-batch 4 \
  --inference-batch 32 --inference-delay-ms 1 \
  --inference-slots "${VGO_SLOTS:-2}" \
  --provider tensorrt --fp16 --warm-inference \
  --overlap-actor-learner --retire-shards \
  --arena-pairs 8 --arena-simulations 256 \
  --seed 31100001 --arena-seed 31105001
