[project]
name = "vgo-training"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.1",
    "onnx>=1.19.0",
    "onnxscript>=0.5.0",
    "torch>=2.13.0",
    "triton-windows>=3.7,<3.8; sys_platform == 'win32'",
]

[project.optional-dependencies]
tensorrt = [
    "tensorrt-cu13-libs==10.16.1.11; sys_platform == 'win32' or sys_platform == 'linux'",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
